Repository cloud-barista/cm-beetle, pull requests merged in 2023-11, with the labels that each got.

#13 [Workflow] Update Swagger REST API doc
  pkg/api/rest/docs/docs.go
  pkg/api/rest/docs/swagger.json
  pkg/api/rest/docs/swagger.yaml
Labels: swagger, automated pr

#15 [Workflow] Update Swagger REST API doc
  pkg/api/rest/docs/docs.go
  pkg/api/rest/docs/swagger.json
  pkg/api/rest/docs/swagger.yaml
Labels: swagger, automated pr

#16 Update CI/CD related parts
  .github/workflows/build-amd64-container-image.yaml
  .github/workflows/continuous-delivery.yaml
  .github/workflows/continuous-integration.yaml
  Dockerfile
  conf/setup.env
  pkg/api/rest/server/common/utility.go
Labels: approved

#22 Update continuous-delivery.yaml
  .github/workflows/continuous-delivery.yaml
Labels: approved

#21 Update README to mention relationship with CB-TB
  README.md
Labels: approved

#23 Update README and related things
  .github/workflows/continuous-delivery.yaml
  Dockerfile
  README.md
  conf/setup.env
  pkg/api/rest/server/migration/migration.go
  pkg/api/rest/server/migration/model.go
  pkg/api/rest/server/server.go
Labels: approved

#24 [Workflow] Update Swagger REST API doc
  pkg/api/rest/docs/docs.go
  pkg/api/rest/docs/swagger.json
  pkg/api/rest/docs/swagger.yaml
Labels: approved, swagger, automated pr

#25 Add how to install swag in README.md
  README.md
Labels: approved

#28 Update README
  README.md
Labels: approved
